### ISSUE TITLE
pyedbglib.hidtransport.hidtransportbase - ERROR - No CMSIS-DAP devices found.

### ISSUE THREAD

**Issue by mcsmark** [microchip-pic-avr-tools/pyedbglib#2]
I use MPLAB SNAP. And i try pymcuprog ping
But i can not connect. Mainly because the used device is not a HID device.
So is there something i miss? Is it a bug? Has this been actual tested with MPLAB SNAP ?

**Comment by xedbg** [comment]
Repost:
Yes, Snap is tested, and it is a HID device if its in AVR / EDBG / CMSIS-DAP mode.
To get it into that mode, use Microchip Studio or MPLABX to make the switch by programming an AVR device.

**Comment by mcsmark** [comment]
Thanks for your reply. And this switch (i need to google how to do it but no problem) will it remain ?
Or must i each time use mplabx to make this switch?
I actually would like to avoid using mplabx at all.

**Comment by xedbg** [comment]
The switch is persistent, and will only switch back if for some reason you program a PIC in MPLABX.

**Comment by mcsmark** [comment]
ok, it was some work : install the mlab-x, then recover the firmware, do an avr project and then a virtual COM port was installed. so the error message is gone now. i get others but i can sort that out now there is communication :-).  thanks again for the help.
