### ISSUE TITLE
DEPRECATION: pyedbglib 2.22.0.7 has a non-standard dependency specifier pyserial

### ISSUE THREAD

**Issue by Kilsgaard** [microchip-pic-avr-tools/pyedbglib#5]
pip 23.2 is issuing the following warning.

DEPRECATION: pyedbglib 2.22.0.7 has a non-standard dependency specifier pyserial>=3.5*. pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of pyedbglib or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063

Think it is an issue that is going to give problems later, if it is not addressed?

**Comment by xedbg** [comment]
Thanks @Kilsgaard - we have the same issue on many of our packages.  We have staged a fix (internally logged as DSG-6132) but have not yet planned a release.  Hopefully by late summer though.

**Comment by pic-avr-github-admin** [comment]
Closed.
